# Generated by Django 4.1.4 on 2023-05-08 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_product", "0001_initial"),
        ("app_cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartdatabase",
            name="good",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_product",
                to="app_product.product",
                verbose_name="Товар",
            ),
        ),
    ]
